[theme]
primaryColor = "#F2C811"  # ה-צהוב של Power BI (לכפתורים ודגשים)
backgroundColor = "#FFFFFF" # רקע נקי לבן
secondaryBackgroundColor = "#F0F2F6" # אפור בהיר מאוד לסרגל הצד
textColor = "#262730" # אפור כהה (ולא שחור מלא) לקריאות מקסימלית
font = "sans serif"

[server]
enableCORS = false